apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mufasa-hpa
  labels:
    app: mufasa
    version: 0.0.1
    backstage.io/kubernetes-id: mufasa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: mufasa
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75